table product
	lineageTag: 9a75bf95-f10a-49af-b1fb-14ef89c93abd

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 28c750fd-3015-4ad3-aab1-222cbbd5a31d
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductCode
		dataType: int64
		formatString: 0
		lineageTag: c1a4cd76-9f65-4c54-b602-ba6a20fcf0da
		summarizeBy: none
		sourceColumn: ProductCode

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: c392efce-63c4-443b-923c-0c703bbb4ba4
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		lineageTag: fc04556f-2be7-4556-932a-9ef846099942
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: e08d176a-1fba-4743-98db-5ba1b0e4c097
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: ff7e5aaf-1b65-427e-91cf-db681b02c8ad
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column WeightUnit
		dataType: string
		lineageTag: 73bc9c88-5022-4acd-a458-1939820a01c6
		summarizeBy: none
		sourceColumn: WeightUnit

		annotation SummarizationSetBy = Automatic

	column Weight
		dataType: double
		lineageTag: aa72f303-eb75-4a32-b977-7d04818fdac3
		summarizeBy: none
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cost
		dataType: double
		lineageTag: a2cca27a-f1b8-49e5-b9ab-3262f8a85078
		summarizeBy: none
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price
		dataType: double
		lineageTag: a13a9806-1441-4204-beb5-8f63173651f8
		summarizeBy: none
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CategoryKey
		dataType: int64
		formatString: 0
		lineageTag: a6530887-08be-4323-a7b5-979cc7fb59fd
		summarizeBy: none
		sourceColumn: CategoryKey

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: fd3f5b0f-a612-40ac-a884-d184c8b8f64e
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	column SubCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 8f0d23e6-b038-4f3f-b6f5-a1ecdb12bd64
		summarizeBy: none
		sourceColumn: SubCategoryKey

		annotation SummarizationSetBy = Automatic

	column SubCategoryName
		dataType: string
		lineageTag: 4c375c9f-b0be-464b-a9cf-72dbc90ff0a7
		summarizeBy: none
		sourceColumn: SubCategoryName

		annotation SummarizationSetBy = Automatic

	partition product = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\Trabajo\Desktop\Datando\Sets de Datos\Contoso\csv-1m\product.csv"),[Delimiter=",", Columns=14, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ProductKey", Int64.Type}, {"ProductCode", Int64.Type}, {"ProductName", type text}, {"Manufacturer", type text}, {"Brand", type text}, {"Color", type text}, {"WeightUnit", type text}, {"Weight", type number}, {"Cost", type number}, {"Price", type number}, {"CategoryKey", Int64.Type}, {"CategoryName", type text}, {"SubCategoryKey", Int64.Type}, {"SubCategoryName", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

